version: '3.8'

services:
  # API Gateway
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    networks:
      - cinema-network
    depends_on:
      - user-service
      - movie-service
      - cinema-service
      - booking-service
      - payment-service
      - coupon-service

  # User Service
  user-service:
    build: ./services/user-service
    ports:
      - "3012:3012"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@user-db/user_db
    networks:
      - cinema-network
    depends_on:
      - user-db

  user-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./services/user-service/user.sql:/docker-entrypoint-initdb.d/init.sql
      - user-db-data:/var/lib/mysql
    networks:
      - cinema-network

  # Movie Service
  movie-service:
    build: ./services/movie-service
    ports:
      - "3010:3010"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@movie-db/movie_db
    networks:
      - cinema-network
    depends_on:
      - movie-db

  movie-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: movie_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./services/movie-service/movie.sql:/docker-entrypoint-initdb.d/init.sql
      - movie-db-data:/var/lib/mysql
    networks:
      - cinema-network

  # Cinema Service
  cinema-service:
    build: ./services/cinema-service
    ports:
      - "3008:3008"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@cinema-db/cinema_db
    networks:
      - cinema-network
    depends_on:
      - cinema-db

  cinema-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./services/cinema-service/cinema.sql:/docker-entrypoint-initdb.d/init.sql
      - cinema-db-data:/var/lib/mysql
    networks:
      - cinema-network

  # Booking Service
  booking-service:
    build: ./services/booking-service
    ports:
      - "3007:3007"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@booking-db/booking_db
    networks:
      - cinema-network
    depends_on:
      - booking-db

  booking-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: booking_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./services/booking-service/booking.sql:/docker-entrypoint-initdb.d/init.sql
      - booking-db-data:/var/lib/mysql
    networks:
      - cinema-network

  # Payment Service
  payment-service:
    build: ./services/payment-service
    ports:
      - "3011:3011"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@payment-db/payment_db
    networks:
      - cinema-network
    depends_on:
      - payment-db

  payment-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./services/payment-service/payment.sql:/docker-entrypoint-initdb.d/init.sql
      - payment-db-data:/var/lib/mysql
    networks:
      - cinema-network

  # Coupon Service
  coupon-service:
    build: ./services/coupon-service
    ports:
      - "3009:3009"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@coupon-db/coupon_db
    networks:
      - cinema-network
    depends_on:
      - coupon-db

  coupon-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: coupon_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./services/coupon-service/coupon.sql:/docker-entrypoint-initdb.d/init.sql
      - coupon-db-data:/var/lib/mysql
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge

volumes:
  user-db-data:
  movie-db-data:
  cinema-db-data:
  booking-db-data:
  payment-db-data:
  coupon-db-data: