version: '3.8'

services:
  # API Gateway
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    networks:
      - cinema-network
    depends_on:
      - user-service
      - movie-service
      - cinema-service
      - booking-service
      - payment-service
      - coupon-service

  # phpMyAdmin untuk akses database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-server
      PMA_USER: user
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - cinema-network
    depends_on:
      - mysql-server

  # Single MySQL Server
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/init-databases.sql:/docker-entrypoint-initdb.d/01-init-databases.sql
      - ./services/user-service/user.sql:/docker-entrypoint-initdb.d/02-user.sql
      - ./services/movie-service/movie.sql:/docker-entrypoint-initdb.d/03-movie.sql
      - ./services/cinema-service/cinema.sql:/docker-entrypoint-initdb.d/04-cinema.sql
      - ./services/booking-service/booking.sql:/docker-entrypoint-initdb.d/05-booking.sql
      - ./services/payment-service/payment.sql:/docker-entrypoint-initdb.d/06-payment.sql
      - ./services/coupon-service/coupon.sql:/docker-entrypoint-initdb.d/07-coupon.sql
      - mysql-data:/var/lib/mysql
    networks:
      - cinema-network

  # User Service
  user-service:
    build: ./services/user-service
    ports:
      - "3012:3012"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql-server/user_db
    networks:
      - cinema-network
    depends_on:
      - mysql-server

  # Movie Service
  movie-service:
    build: ./services/movie-service
    ports:
      - "3010:3010"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql-server/movie_db
    networks:
      - cinema-network
    depends_on:
      - mysql-server

  # Cinema Service
  cinema-service:
    build: ./services/cinema-service
    ports:
      - "3008:3008"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql-server/cinema_db
    networks:
      - cinema-network
    depends_on:
      - mysql-server

  # Booking Service
  booking-service:
    build: ./services/booking-service
    ports:
      - "3007:3007"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql-server/booking_db
    networks:
      - cinema-network
    depends_on:
      - mysql-server

  # Payment Service
  payment-service:
    build: ./services/payment-service
    ports:
      - "3011:3011"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql-server/payment_db
    networks:
      - cinema-network
    depends_on:
      - mysql-server

  # Coupon Service
  coupon-service:
    build: ./services/coupon-service
    ports:
      - "3009:3009"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql-server/coupon_db
    networks:
      - cinema-network
    depends_on:
      - mysql-server

networks:
  cinema-network:
    driver: bridge

volumes:
  mysql-data: